.TH "DatabaseTests" 3 "Śr, 26 sty 2022" "Zamawianie Rolek" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseTests \- Klasa zawierająca testy związane z klasą Database - bazą danych, przechowującą informacje o kontach użytkowników i wiatach\&.  

.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.RI "Funkcja setup, inicjalizująca bazę danych przed każdym wywołanym testem\&. "
.ti -1c
.RI "void \fBAccountExistsAfterRegistration\fP ()"
.br
.RI "Test sprawdzający, czy po rejestracji konta znajduje się ono w bazie danych\&. "
.ti -1c
.RI "void \fBShedExistsAfterAdd\fP ()"
.br
.RI "Test sprawdzający, czy po dodaniu nowej wiaty do bazy danych jest ona zapisana\&. "
.ti -1c
.RI "void \fBThrowsForNullParameter\fP ()"
.br
.RI "Test sprawdzający, czy funkcja odpowiedzialna za dodanie obiektu do bazy danych wyrzuca wyjątek w przypadku danych wejściowych będących null\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa zawierająca testy związane z klasą Database - bazą danych, przechowującą informacje o kontach użytkowników i wiatach\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Zamawianie Rolek\&.
