.TH "RideTests" 3 "Śr, 26 sty 2022" "Zamawianie Rolek" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RideTests \- Klasa zawierająca testy związane z klasą \fBRide\fP - przejazdem, obliczaniem ceny i długości przejazdu, oraz trybem Turbo\&.  

.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.RI "Funkcja setup, inicjalizująca bazę danych przed każdym wywołanym testem, oraz inicjalizująca obiekt \fBAccount\fP, wykorzystywany przez testy\&. "
.ti -1c
.RI "void \fBEvaluatesPriceCorrectly\fP ()"
.br
.RI "Test sprawdzający, czy cena za przejazd wrotkami jest obliczana poprawnie\&. "
.ti -1c
.RI "void \fBEvaluatesTimeCorrectly\fP ()"
.br
.RI "Test sprawdzający, czy czas przejazdu wrotkami (w minutach) jest obliczany poprawnie\&. "
.ti -1c
.RI "void \fBTurboModeSwitchesCorrectly\fP ()"
.br
.RI "Test sprawdzający, czy przełączanie trybu Turbo we wrotkach działa poprawnie\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa zawierająca testy związane z klasą \fBRide\fP - przejazdem, obliczaniem ceny i długości przejazdu, oraz trybem Turbo\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Zamawianie Rolek\&.
