.TH "UserProfileTests" 3 "Śr, 26 sty 2022" "Zamawianie Rolek" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserProfileTests \- Klasa zawierająca testy związane z klasą \fBUserProfile\fP - profilem użytkownika w ramach konta\&.  

.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.RI "Funkcja setup, inicjalizująca bazę danych przed każdym wywołanym testem\&. "
.ti -1c
.RI "void \fBProfileExistsAfterCreating\fP ()"
.br
.RI "Test sprawdzający, czy po utworzeniu profilu użytkownika jest on przypisany do konta, oraz czy jest on aktualnie wybranym profilem\&. "
.ti -1c
.RI "void \fBThrowsForInvalidInput\fP ()"
.br
.RI "Test sprawdzający, czy funkcja tworząca profil użytkownika wyrzuca wyjątek dla niepoprawnych danych wejściowych\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa zawierająca testy związane z klasą \fBUserProfile\fP - profilem użytkownika w ramach konta\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Zamawianie Rolek\&.
